### ISSUE TITLE
Rubocop?

### ISSUE THREAD

**Issue by soumyaray** [RubyStarts3/YPBT#3]
Run rubocop on all your code.  You have strange indentation and other issues!

**Comment by luyimin** [comment]
We will revise our code, and rubocop it soon, about 1 day :<

**Comment by luyimin** [comment]
Soumya, I have revised all code to fit our idea, then I already run rubocop and fix strange indentation, please check it out, thank you.  :)

**Comment by soumyaray** [comment]
Hi, I cloned your master branch and ran rubocop on `lib/` folder:

```
$ rubocop lib
Inspecting 3 files
EEE

Offenses:

lib/comment_threads.rb:5:1: E: module definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
module VideoCommentThreads
^^^^^^
lib/comment_threads.rb:7:3: E: class definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
  class CommentThreads
  ^^^^^
lib/comment_threads.rb:10:42: E: unexpected token tCOMMA
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
    def initialize(youtube_api, video_id:, api_key:)
                                         ^
lib/display_text.rb:4:1: E: module definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
module VideoCommentThreads
^^^^^^
lib/display_text.rb:6:3: E: class definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
  class DisplayText
  ^^^^^
lib/display_text.rb:9:42: E: unexpected token tCOMMA
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
    def initialize(youtube_api, video_id:, api_key:, fields:)
                                         ^
lib/youtube_api.rb:4:1: E: module definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
module VideoCommentThreads
^^^^^^
lib/youtube_api.rb:6:3: E: class definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
  class YtApi
  ^^^^^
lib/youtube_api.rb:16:28: E: unexpected token tRPAREN
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
    def initialize(api_key:)
                           ^
```

**Comment by luyimin** [comment]
Excuse me, I have no idea what `Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops` means, what's wrong with `module` and `class` ? Last night, I had thought it is not error, can give me some ideas? thank :)

**Comment by soumyaray** [comment]
ok, i've got a fix but gimme a couple of hours to get back to you!  in middle of a meeting right now :D

**Comment by soumyaray** [comment]
I've issues a pull request about this issue -- please take a look at my comments to it!!!

**Comment by luyimin** [comment]
oh! That is the reason why it happened warning before! Next time I will create `.rubocup.yml` file.
I will fix new errors later, thank you Soumya.

**Comment by soumyaray** [comment]
You bet!  I have issued a "pull request" to your team.  Feel free to merge it into master on Github.  Tell me if you want more help on how to do this.  It has already implemented the change of adding a `.rubocop.yml` file to your repo :)

**Comment by luyimin** [comment]
Soumya, I already merge it into master, and I've fixed all new warnings, please check it out again, it is so sorry to bother you many times, thanks for everything you do!!

**Comment by soumyaray** [comment]
AWESOME!
