### ISSUE TITLE
adas file?

### ISSUE THREAD

**Issue by soumyaray** [RubyStarts3/YPBT#4]
Clean up files that are not for others to see (like adas file).

**Comment by luyimin** [comment]
Ok, Today I will revise my code, sorry.

呂奕旻

2016年10月18日 12:18，"Soumya Ray" notifications@github.com寫道：

**Comment by soumyaray** [comment]
No problem!  Let me know on Github when you've resolved it :)

**Comment by luyimin** [comment]
Soumya, I have delete it, sorry for my carelessness.

**Comment by soumyaray** [comment]
great!
