### ISSUE TITLE
Redundant line?

### ISSUE THREAD

**Issue by soumyaray** [RubyStarts3/YPBT#9]
Take a look at: https://github.com/RubyStarts3/Ytapi/blob/master/lib/comment_threads.rb#L19-L20

Can't it just become:

```
@comment_threads = @youtube_api.comment_threads_info(@video_id)
```

Feel free to close this issue when you feel you've resolved it. :)

Also, if you are going to use Youtube in your project, consider making more classes like 'Thread' or 'Comment' that encapsulates these objects more clearly instead of just returning deeply nested json :)

**Comment by luyimin** [comment]
Ok, I've updated it. 
That is my first time to do this work, still looking for good way to improve it. I also concerned about the "nested" json, and try to dig target data out of this nested array and hash, can you give me some keywords to search?
